### ISSUE TITLE
Replace the CustomCommand system with a Tag system

### ISSUE THREAD

**Issue by GreemDev** [Polyhaze/Volte#23]
Similar to [Rapptz/RoboDanny](https://github.com/Rapptz/RoboDanny); this would allow for placeholders as well so you can mention the user calling the tag, etc.

**Comment by adx59** [comment]
Yes; in fact, I could probably throw together some more syntax, making it similar to Tat's tag system

**Comment by GreemDev** [comment]
~~@adx59 Tat's? :thonking:~~

disregard, you mean tatsumaki

**Comment by adx59** [comment]
Lmfao

**Comment by GreemDev** [comment]
added in the most recent commit
