### ISSUE TITLE
Change ServerInfo to more accurately show CreatedAt

### ISSUE THREAD

**Issue by GreemDev** [Polyhaze/Volte#24]
currently it shows it in year-accuracy, e.g. "one year ago" which isn't very informational. This issue suggests that it be changed to show months and days maybe.

**Comment by jacksonrakena** [comment]
If you’re using Humanizer, you can provide an integer to DateTimeOffset#Humanize which determines the precision of the result

**Comment by GreemDev** [comment]
@thecatitude Last time I checked, Humanize() has a precision int parameter. I used it in the uptime command iirc
