### ISSUE TITLE
Add bot permission checks for commands that require them and wrap DMs in try/catch.

### ISSUE THREAD

**Issue by Quahu** [Polyhaze/Volte#27]
Some commands, like `Ban`, require the bot to have given permissions (BanMembers in this case). There's no checks for those permissions in the code and the bot can end up DMing a member saying they were banned even though such action wouldn't be able to take place.

All commands such as the `Ban` command should try/catch DMing the user as it may fail, if the user has disabled messages from guild members.

**Comment by GreemDev** [comment]
This will be fixed in a few hours when I am at my PC again. It's currently 4:43 AM and as such I have no mental capacity to fix this. 

Thanks for the issue!
