### ISSUE TITLE
Bot still sends error message on insufficient permissions result

### ISSUE THREAD

**Issue by jacksonrakena** [Polyhaze/Volte#31]
Greem can't code if his life depended on it

![image](https://user-images.githubusercontent.com/44521335/57562705-3711d300-73e9-11e9-9fe8-60b2f41d67ec.png)

**Comment by GreemDev** [comment]
can't argue with facts

**Comment by GreemDev** [comment]
fixed in [`d0f28c9`](https://github.com/GreemDev/Volte/commit/d0f28c9886845c2ee1c4fffe734018d12d28e050)

**Comment by jacksonrakena** [comment]
uwu
