### ISSUE TITLE
Poll with long title/question

### ISSUE THREAD

**Issue by MarkusKgit** [Polyhaze/Volte#35]
When you do a poll and the question (the first option in the list) is longer than 256 characters an exception will be raised because the poll question is used as the [title for the returned embed](https://github.com/Ultz/Volte/blob/ccafca0aa2da06a1a001d0495bfc29380713e3d1/src/Commands/Modules/Utility/PollCommand.cs#L19) which is [limited to 256 characters](https://discordapp.com/developers/docs/resources/channel#embed-limits)

Proposed solutions:
- Move the question in the description and make the individual answers fields
- Add a check for character limit and warn user about the question (or answers) being too long thus giving a more user friendly experience

**Comment by GreemDev** [comment]
I'll take a look at ways we can tackle this tomorrow. Thanks for opening this, as always.
