### ISSUE TITLE
christ almighty

### ISSUE THREAD

**Issue by Perksey** [Polyhaze/Volte#39]
The readme references Midnight when the bot is actually called Adora

**Comment by GreemDev** [comment]
@abyssal why on earth do you rename your bot so much

**Comment by jacksonrakena** [comment]
why do i still exist @GreemDev

**Comment by theprogwizard** [comment]
Just saw that the prefix used is a dot and not a dollar sign as stated under Volte bot member list

**Comment by GreemDev** [comment]
What do you mean?

**Comment by theprogwizard** [comment]
![volte](https://user-images.githubusercontent.com/14824655/82257663-6de8c600-9926-11ea-835f-a14059232a5d.PNG)

but when you have to actually call a command you have to write '.h' for example

**Comment by GreemDev** [comment]
That's a per-guild thing; Volte's public prefix is $, your guild's prefix must be a .

Unfortunately I cannot set the status for every guild, it's just not possible

**Comment by Perksey** [comment]
We should probably close this issue if the original issue isn't being fixed
