### ISSUE TITLE
the logo in the readme is very BIG

### ISSUE THREAD

**Issue by Perksey** [Polyhaze/Volte#40]
plzfix

**Comment by GreemDev** [comment]
ok and

**Comment by Perksey** [comment]
i can't read the readme because the logo takes up the whole page lmao

![image](https://user-images.githubusercontent.com/11160611/87038264-65ee2980-c1e5-11ea-87dd-a1100b108b22.png)

![image](https://user-images.githubusercontent.com/11160611/87038340-7c948080-c1e5-11ea-801f-a00a8a2585a0.png)
